### ISSUE TITLE
It's not exactly issue with  program.  But you .bashrc count line does not work properly. 

### ISSUE THREAD

**Issue by polinom** [sjl/t#7]
Did not know where to write but. So i decide here.
After i put this in .profile on Lion.

`export PS1="[$(t | wc -l | sed -e's/ *//')] $PS1"`

It's behavior is strange. 
1. Does not changes the count after i delete task. 
2. If I do source twice it vill add one more count.

`[1] [1] [1] [2] Igors-MacBook-Pro:tasks polinom$`

here i run `source .profile` 4 times.

**Comment by joelittlejohn** [comment]
This is a bash question not a t issue so I think it can be closed. @polinom you are _evaluating_ `t | wc -l | sed -e's/ *//'` once when you export your PS1, so the number never changes afterwards. You can see the problem if you try `echo $PS1`.

You need to instead **set the expression** into the PS1 env var so that it can be evaluated later. You either need to escape the `$` chars like `\$` or replace the double quote marks with single quotes. Since it looks like you do _want_ to evaluate the $PS1 at the end of the expression (you want the original PS1 to be printed there) I think you need to choose the escaping option.

**Comment by pendashteh** [comment]
Just sent a pull request to fix this. In the meantime, replace the line with the following:
`export PS1='[$(t | wc -l | sed -e"s/ *//")]'" $PS1"`
